### ISSUE TITLE
2FA has been activated

### ISSUE THREAD

**Issue by leeyuentuen** [pypolestar/polestar_api#117]
on the polestar app, 2 factor authentication has been activated. i suppose the api should soon need extra change

![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/9de2c74f-7086-443e-95d2-c3d11e28a1a5)

**Comment by jschlyter** [comment]
2FA does not seem to be required for web logins, only from within the mobile app. Closing this issue for now, but we should keep monitoring for changes and possibly move to a real login (although this most likely requires some coordination with Polestar).
