### ISSUE TITLE
Charging current and voltage also in api?

### ISSUE THREAD

**Issue by mountainbikert** [pypolestar/polestar_api#134]
In the current api charging current and voltage are shown as not implemented yet. I got an update last week and the app should now show it (but it doesn't yet, although there are screenshots on polestar2 forum where people see them). Is this something that can be shown in HA?

**Comment by niklasvieth** [comment]
You need the P3.0.3 update installed on your vehicle, then it should work both in the app and in homeassistant

**Comment by leeyuentuen** [comment]
the value has been showed, but missing the voltage and watt

on this release it should work:
[1.6.11](https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.11)

![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/a76d4947-6456-4cf0-afbb-a67cac4e7075)

**Comment by palengh** [comment]
Works great here :-)
<img width="483" alt="image" src="https://github.com/leeyuentuen/polestar_api/assets/12332161/04c5ec43-80eb-4c34-87ee-bcfb0ad783b8">

**Comment by leeyuentuen** [comment]
still got issue here,.if not charging, it keeps the latest value instead of 0

**Comment by leeyuentuen** [comment]
> still got issue here,.if not charging, it keeps the latest value instead of 0

should be now fix in the new beta version:
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/e2a8679a-2397-4a6e-a924-f5f0c15ee417)

https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.12
