### ISSUE TITLE
Unexpected error creating api

### ISSUE THREAD

**Issue by leighpilkington** [pypolestar/polestar_api#135]
G’day all,

Got my polestar today and registered the phone etc, my account is all good to go and I can connect to the car through the phone.

However, after restarting home assistant, confirming connection, etc, when I put in my credentials at set up I get a “ Unexpected error creating api” error returned and it kicks me out.

Any ideas of what I should do?

Cheers,

Leigh

**Comment by leeyuentuen** [comment]
can you check in the log?

**Comment by leighpilkington** [comment]
I thought that might have been it initially but when I tried before picking up the car, I got a clear “there are no cars” error.  

The log does suggest otherwise though!!

This error originated from a custom integration.

Logger: custom_components.polestar_api.pypolestar.polestar
Source: /config/custom_components/polestar_api/pypolestar/polestar.py:121
integration: Polestar API (documentation)
First occurred: 7:28:50 PM (3 occurrences)
Last logged: 8:41:53 PM

No cars found in account
NoneType: None


It’s a government lease so I guess it could mean that the car will never show up in my account..?..

**Comment by leeyuentuen** [comment]
i don't think it should be an issue,
just ask polestar to link the car to your account see this post:
https://github.com/leeyuentuen/polestar_api/issues/133#issuecomment-2073220944

you should normally see your car in your polestar account then:
https://github.com/leeyuentuen/polestar_api/issues/133#issuecomment-2071059988 
like on this URL: https://www.polestar.com/uk/login/cars

**Comment by leighpilkington** [comment]
I’ll give it a go after I wait a few days.  I only signed the paperwork today (and literally it was paper so I will give it some time to filter through).  Thanks for pointing me in the right direction.  Patience and then a call if it fails and I’ll see how it goes.
