### ISSUE TITLE
Sensor for software version has wrong format

### ISSUE THREAD

**Issue by palengh** [pypolestar/polestar_api#136]
The ´sensor.polestar_xxxx_software_version´ shows ´03.00´, but should be formatted like this ---> ´3.0.3´
I really appreciate your great job with this integration, @leeyuentuen :-)

**Comment by leeyuentuen** [comment]
i think it is something that i just 1-1 take over from the API.


when the version was 2.14.3, I've got this
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/632f405f-7c57-4ebd-9ff6-4f29014e2e0d)
