### ISSUE TITLE
Sensors marked as unknown

### ISSUE THREAD

**Issue by Marius13081999** [pypolestar/polestar_api#138]
Hello,
I was able to successfully connect my Polestar 2 to HA. Unfortunately, almost all sensors are not available, except the API token, VIN, internal vehicle number and my license plate. 
![image](https://github.com/leeyuentuen/polestar_api/assets/111448991/e8f97d08-1c90-4f0f-9fc1-8cc37cdd88d4)

At first I thought I would have to switch the vehicle on and drive a lap. But the conditions haven't changed. Unfortunately, removing and re-adding in the IT manner :) didn't work either.

Does anyone know what to do or have the same problem?

**Comment by leeyuentuen** [comment]
have you check what you see in the log for error or warning?

**Comment by jschlyter** [comment]
Is this still an issue? If not please close the issue.
