### ISSUE TITLE
Lease car not on account

### ISSUE THREAD

**Issue by frameset** [pypolestar/polestar_api#140]
Hello. My Polestar is a lease from a third party company, not through Polestar directly. This means the car is not showing on the website when I log in. I contacted Polestar and they say that because I'm leasing via a third party there's nothing they can do to add the car to my account.

I do have the car on my Polestar android app (signed in with my P*ID), so I can see the battery status etc there.

Is there anything I can do to add this HA integration? Possibly via the VIN? I mostly want to grab the SoC to set my smart charger.

**Comment by leeyuentuen** [comment]
check this issue: https://github.com/leeyuentuen/polestar_api/issues/105

**Comment by frameset** [comment]
As I said in my post, I've contacted Polestar and they cannot add it to my account, which was the resolution in issue #105

**Comment by leeyuentuen** [comment]
my car is also not directly from polestar.

i'm also driving (belgium) with leasing company from arval. I've just got the full access of the car here.

have you try to add the car in the webinterface
https://www.polestar.com/uk/login/cars

**Comment by frameset** [comment]
That's mildly amusing, mine is also from Arval 
I did try that, but it tells me the VIN is already assigned to another account.
My support request was as follows:
>>Hi all,
>>
>>Thanks for calling me earlier on.
>>
>>I'm a technology worker and I was looking to use the polestar API to query facts about the car programmatically. Things like state of charge, etc.
>>
>>I can then use this data to work with home automations and set my Ohme home charger to the correct schedule or amount, amongst other things.
>>
>>The problem is that from a Polestar account perspective I don't "own" the car, so I can't query it using my credentials. If I try to add the VIN to my Polestar account, I get an error message because it's already assigned, presumably to the lease company's account.
>>
>>Looking at Polestar enthusiast discussion boards, lease car users have reported success when contacted Polestar support to have this added to their account.
>>
>>Stephen suggested this may be complicated due to my leasing through a 3rd party company rather than directly through Polestar.
>>
>>Any help would be appreciated.
>>
>>Regards,
>>Mark 

>Good afternoon Mark,
>
>Thank you for your enquiry,
>
>Unfortunately as your car is provided through a lease company we are not able to assist you with this. 
>
>If there is anything else we can help you with, please don't hesitate to get in touch on 0808 134 8372 or reply via this email.
>
>Many thanks
>
>Kind regards,
>Stephen
>—
>Polestar

How did you word your request to Polestar support to get them to add it to your ID?

**Comment by leeyuentuen** [comment]
it was a long time ago that I've add the them.

what I remember, is I thought I had first create a polestar ID, and then on the first time in the car, they added that id on the car I thought.

maybe try on this URL: https://www.polestar.com/uk/login/cars



![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/38605940-d382-4f9a-a564-ba16ca7850b7)

and put the vin here to transfer the ownership?

![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/1700616f-c31c-41a4-8e74-45057a7c981f)


or maybe try again to send a message to polestar, maybe someone else in polestar will do it.
