### ISSUE TITLE
(NOTICE) Future of Polestar API

### ISSUE THREAD

**Issue by leeyuentuen** [pypolestar/polestar_api#145]
I'm no longer an owner of a Polestar (return of my lease car). So extra features should not be possible. (unless my new lease car is also a Polestar) Thanks everyone for the support!

**Comment by dgomes** [comment]
That's a shame :(

I was planing on pushing you to go for a contribution to HA, and make this official :)

**Comment by leeyuentuen** [comment]
> That's a shame :(
> 
> I was planing on pushing you to go for a contribution to HA, and make this official :)

ya, it happened that can't be changed, but if someone can share his/her account though private mail, then I can still continue with this API.

**Comment by wouterhardeman** [comment]
Fingers crossed you get to keep the pleasure of driving a Polestar. :crossed_fingers: In any case, thanks for your efforts in creating this integration! :heart: 

In case of any breaking issues I'll try to fix them (but no promises :wink:). Hopefully you will keep an eye out to merge them. Otherwise we'll figure out something else :smile:

Thanks again for your efforts!

**Comment by palengh** [comment]
Thanks for your effort🤩
Hope someone will/can continue maintaining and Developer your code.

**Comment by jschlyter** [comment]
I'm interesting in taking maintainer of the component and the python library.

xref: https://github.com/leeyuentuen/pypolestar/issues/8

**Comment by leeyuentuen** [comment]
i think you can just make MR on both branch?

**Comment by jschlyter** [comment]
I'll create a dedicated github organisation for long term maintenance, will let you know when this is done.

**Comment by jschlyter** [comment]
> > I'll create a dedicated github organisation for long term maintenance, will let you know when this is done.
> 
> Is this still in your plans? Would be great if someone could take over the maintenance of this one. 👍

Yes, although the API currently does not work at all due to changes in the backend (e.g., the OP is now behind Cloudflare). I'll try to reach out to my contacts at Polestar and see what's cooking.

**Comment by jschlyter** [comment]
I've now created https://github.com/pypolestar to host the integration and the Python module.

**Comment by jschlyter** [comment]
Once https://github.com/leeyuentuen/polestar_api has been transferred to https://github.com/pypolestar/polestar_api, I'm planning to include it in the official HACS list of integrations as well as updating some dependencies. As long as we use the repository transfer feature, the move should be seamless for existing users (Github keeps tracks of move/rename across organizations).

**Comment by jschlyter** [comment]
@leeyuentuen - please get in touch via email, my address is in my profile.

**Comment by leeyuentuen** [comment]
> @leeyuentuen - please get in touch via email, my address is in my profile.

let me take a look at the weekend.

what is the different using this repo instead of moving?

**Comment by jschlyter** [comment]
> what is the different using this repo instead of moving?

Moving to a separate organisation allows better control of contributors, security settings, discussions and integrations not possible with a personal account. We could also have multiple administrators and transition between maintainers are easier.

**Comment by leeyuentuen** [comment]
> > what is the different using this repo instead of moving?
> 
> Moving to a separate organisation allows better control of contributors, security settings, discussions and integrations not possible with a personal account. We could also have multiple administrators and transition between maintainers are easier.

if i transfer it, all the users that are now using on hacs should get issue on it for update?

**Comment by jschlyter** [comment]
> if i transfer it, all the users that are now using on hacs should get issue on it for update?

I believe Github will handle the transition gracefully and will allow fetching from both the old and the new URL.

**Comment by leeyuentuen** [comment]
i've just transfer. but don't have time to check if everything is still working

**Comment by jschlyter** [comment]
Repository moved, all good
