### ISSUE TITLE
Not possible to have two Polestars configured at the same time?

### ISSUE THREAD

**Issue by palengh** [pypolestar/polestar_api#150]
Could be an issue, or by design.

Just wanted you guys to know I have two Polestars defined in my HA installation. My new Polestar 4 seems to update, while my Polestar 2 became unavailable. Good thing the PS4 is still in transit, stored on the quay in Zeebrugge, Belgium. Nice to see it's "alive", but what happened to the data from my PS2?

<img width="1011" alt="image" src="https://github.com/leeyuentuen/polestar_api/assets/12332161/86d14619-70da-4e13-bbe7-f662bbd4c152">

**Comment by palengh** [comment]
same as #128

**Comment by puttemanp** [comment]
Same issue. Have a P3 in transit, P2 I'm driving. P3 showed up in the integration and at the same time P2 became unavailable.
I suspect this issue exists with all owners with more than one Polestar.

**Comment by leeyuentuen** [comment]
If I could have the credentials of the person who got multiple polestars on the account, I could debug the issue and create something. Normally I have only access to the information, but I can't control/unlock the car.

But I understand that it is not easy to share this credential to someone on the internet that you don't know them. So the issue can't be fixed (for me) without this information

**Comment by puttemanp** [comment]
I can give you my login/pw combination privately, but you'll have to be quick as my P2 will be removed on Sept. 24 as I'll take delivery of my P3 (and that will give you the occasion to check your integration for compatibility with P3).

**Comment by leeyuentuen** [comment]
> I can give you my login/pw combination privately, but you'll have to be quick as my P2 will be removed on Sept. 24 as I'll take delivery of my P3 (and that will give you the occasion to check your integration for compatibility with P3).

send me an email with the credential to: leeyuentuen[at]gmail.com

Thanks. maybe I can take a look in the next few days (but not guarantee)

**Comment by puttemanp** [comment]
Done :)

**Comment by leeyuentuen** [comment]
I've temporarily done a dirty way to get both of the cars.

We need to refactor them better. but see what the feedback is on the beta version:

https://github.com/leeyuentuen/polestar_api/releases/tag/1.7.0

**Comment by puttemanp** [comment]
Maybe a dirty way, but it works... Both cars detected after installation of 1.7.0 (don't forget to restart HA as I first did) and all entities present!

**Comment by leeyuentuen** [comment]
@puttemanp thanks again for the credential for testing. If I have more time, I can investigate them more and make them more cleaner way

**Comment by remcotjeerdsma** [comment]
Thank you for fixing this so quickly; also helped me! And in general, thanks for the work on this integration.
