### ISSUE TITLE
Unexpected error creating api.

### ISSUE THREAD

**Issue by jarkodesign** [pypolestar/polestar_api#155]
Hi, 

Trying to log in and i get that error.

**Comment by jarkodesign** [comment]
Oh, and i live in Finland so i guess i´m trying to connect Polestar europe server, if that matters?

**Comment by taskinen** [comment]
@jarkodesign Have you tried with the latest version 1.6.15?

If you have, and still have problems, please post the appropriate error message from the Home Assistant logs.

**Comment by jarkodesign** [comment]
> @jarkodesign Have you tried with the latest version 1.6.15?
> 
> If you have, and still have problems, please post the appropriate error message from the Home Assistant logs.

Moi,
En löydä lokista / historiasta mitään tähän viittaavaa. 1.6.15 on käytössä, pääsen kirjautumaan polestarin sivuille yms hyvin.

**Comment by richard5mith** [comment]
Just tried and got the same error.

* I can login fine to the URL in the README
* My app certainly shows cars

```
2024-09-20 15:41:52.750 ERROR (MainThread) [custom_components.polestar_api.pypolestar.polestar] No cars found in account
NoneType: None
2024-09-20 15:41:52.750 ERROR (MainThread) [custom_components.polestar_api.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 43, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 47, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 128, in _get_vehicle_data
    raise PolestarNoDataException("No cars found in account")
custom_components.polestar_api.pypolestar.exception.PolestarNoDataException: No cars found in account
```

**Comment by leeyuentuen** [comment]
if you just login on polestar website:
https://www.polestar.com/nl-be/login/profile/
do you see there your car?

**Comment by richard5mith** [comment]
No. It's not there. And I can't add it either, it gives me an error with a bunch of possibilities. One of them is that it's a lease (which it is), another option is that it has already been added (which It has, to the app).

So I'm not sure I understand their system. I even logged out of the app and logged back in, and my car is there. But on the website, it's not.

**Comment by leeyuentuen** [comment]
> No. It's not there. And I can't add it either, it gives me an error with a bunch of possibilities. One of them is that it's a lease (which it is), another option is that it has already been added (which It has, to the app).
> 
> So I'm not sure I understand their system. I even logged out of the app and logged back in, and my car is there. But on the website, it's not.

Send a mail to polestar to link them on your account.

duplicate issue like here: https://github.com/leeyuentuen/polestar_api/issues/90 
https://github.com/leeyuentuen/polestar_api/issues/133

**Comment by taskinen** [comment]
I might be just making things more complex, but I remember when my car was not yet converted to the right market area by the service center, and was still in the previous owner's account, it was not visible in the web but I could add it to my phone app and control it there.
