### ISSUE TITLE
Unable to access server

### ISSUE THREAD

**Issue by motionist** [pypolestar/polestar_api#195]
Hi,

Earlier today, the API stopped providing information.

I get the following logs relating to Polestar

024-11-06 12:58:26.871 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration polestar_api which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-06 12:58:32.852 ERROR (MainThread) [custom_components.polestar_api.pypolestar.auth] Auth Token Error: <Response [200 OK]>
2024-11-06 12:58:32.852 ERROR (MainThread) [custom_components.polestar_api.pypolestar.polestar] Auth Exception: Error getting token
File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 57, in async_init
File "/config/custom_components/polestar_api/pypolestar/auth.py", line 89, in get_token
raise PolestarAuthException("Error getting token", result.status_code)
custom_components.polestar_api.pypolestar.exception.PolestarAuthException: Error getting token
2024-11-06 13:53:55.513 ERROR (MainThread) [custom_components.polestar_api.pypolestar.auth] Auth Token Error: <Response [200 OK]>
2024-11-06 13:53:55.514 ERROR (MainThread) [custom_components.polestar_api.pypolestar.polestar] Auth Exception: Error getting token
File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 57, in async_init
File "/config/custom_components/polestar_api/pypolestar/auth.py", line 89, in get_token
raise PolestarAuthException("Error getting token", result.status_code)
custom_components.polestar_api.pypolestar.exception.PolestarAuthException: Error getting token
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
2024-11-06 14:11:52.058 ERROR (MainThread) [custom_components.polestar_api.pypolestar.auth] Auth Token Error: <Response [200 OK]>
2024-11-06 14:11:52.058 ERROR (MainThread) [custom_components.polestar_api.pypolestar.polestar] Auth Exception: Error getting token
File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 57, in async_init
File "/config/custom_components/polestar_api/pypolestar/auth.py", line 89, in get_token
raise PolestarAuthException("Error getting token", result.status_code)
custom_components.polestar_api.pypolestar.exception.PolestarAuthException: Error getting token
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>
{% set soc = state_attr('sensor.polestar_8561_battery_charge_level','EV SOC') | float -%} {% set tsoc = state_attr('sensor.polestar_8561_battery_charge_level','EV target SOC') | float -%} {% set speed = states.number.ev_smart_charging_2_charging_speed.state | float -%} <table width=100%><tr><td width=80%>Resterende estimeret ladetid:</td> <td width=15% align=right>{{ ((tsoc-soc)/speed*60) | int }} min. </td></tr></table>

**Comment by jschlyter** [comment]
The authentication backend function `getAuthToken` no longer works as before. This may be a temporary error or a deliberate change - I don't know yet.
