### ISSUE TITLE
Polestar authentication broken

### ISSUE THREAD

**Issue by jschlyter** [pypolestar/polestar_api#197]
Polestar has changed their authentication interface blocking all API access until fixed.

**Comment by jschlyter** [comment]
Any advice from @leeyuentuen?

**Comment by D-on-GitHub** [comment]
Error given in Home Assistant:

2024-11-06 20:11:29.851 ERROR (MainThread) [custom_components.polestar_api.pypolestar.auth] <Response [200 OK]>
2024-11-06 20:11:29.851 WARNING (MainThread) [custom_components.polestar_api.pypolestar.polestar] Auth Exception: Error getting token

**Comment by wouterhardeman** [comment]
I don't see any big differences other than that the client_id of the webapp has changed. It's now `l3oopkc_10` instead of `polmystar`. Maybe just changing that will work.

Also important to note: I logged in on the website and it prompted me to accept the updated terms and conditions. Maybe they just updated this to ensure everybody accepts it.

**Comment by jschlyter** [comment]
Possible fix in #198, works here

**Comment by dirkbonhomme** [comment]
It looks like the access tokens for the new client_id are only valid for 5mins. If anyone finds a workaround, let me know please ;)

**Comment by jschlyter** [comment]
As soon as I can get confirmation that the fix works for other, I'll merge and make a new release. You can test locally using:

```
git clone -b client_id_terms_and_conditions https://github.com/jschlyter/polestar_api.git
cd polestar_api
docker compose up
```
This should give you a local home assistant instance on `http://localhost:8123`.

**Comment by leeyuentuen** [comment]
@jschlyter you found the root cause? Otherwise it is only debugging.

Shame on polestar why change this things without improvement

**Comment by jschlyter** [comment]
> @jschlyter you found the root cause? Otherwise it is only debugging.

Yes, they changed the client ID and suddenly started to require some sort of terms and conditions. Probably for a good reason, but not helping integrations like ours. I'll try to reach out and see if I can find someone with clue within Polestar.
