### ISSUE TITLE
API login stopped working

### ISSUE THREAD

**Issue by joba-1** [pypolestar/polestar_api#201]
Hi

I use your integration with ha 2024/6 since several months unchanged. It worked great!
Yesterday it stopped working.
I removed the device, updated to the latest master, restarted ha and gave email, pw and vin.
Unfortunately it did not help. Maybe the login process at polestar has changed?

`2024-11-06 21:17:56.928 ERROR (MainThread) [custom_components.polestar_api.pypolestar.auth] Auth Token Error: {"errors":[{"message":"An internal error has occured.","path":["getAuthToken"],"extensions":{"code":"BAD_USER_INPUT","exception":{"stacktrace":["UserInputError: An internal error has occured.","    at jZi (/var/task/src/functions/auth/handler.js:1381:2697051)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async KZi (/var/task/src/functions/auth/handler.js:1381:2697884)","    at async getAuthToken (/var/task/src/functions/auth/handler.js:1381:2724149)"],"message":"An internal error has occured.","locations":[{"line":1,"column":44}],"path":["getAuthToken"]},"serviceName":"auth"}}],"data":{"getAuthToken":null}}
`

**Comment by jschlyter** [comment]
Please try the latest release - Polestar broke the authentication earlier today.

**Comment by joba-1** [comment]
Installed release 1.8.0 and it works again. Thank you!

**Comment by kp-bit** [comment]
> Installed release 1.8.0 and it works again. Thank you!

Same here, thanks for quick fix!
