### ISSUE TITLE
Odometer reading seems to be missing decimals

### ISSUE THREAD

**Issue by 3shirts** [pypolestar/polestar_api#203]
Since 1.8.0 the odometer reading is over by a factor of 100. It currently reads 23,555,702 when it should be 23555.70

**Comment by 3shirts** [comment]
Huh, never mind. It just fixed itself!

**Comment by kp-bit** [comment]
> Since 1.8.0 the odometer reading is over by a factor of 100. It currently reads 23,555,702 when it should be 23555.70

Just set unit of measurement to km (or miles) and you're good
