### ISSUE TITLE
Increase (default) poll interval and/or configurable

### ISSUE THREAD

**Issue by wouterhardeman** [pypolestar/polestar_api#209]
Currently the integration polls the API every 15 seconds. Sometimes this will result in requests being blocked by Cloudflare.

If every user polls every 15 seconds it's more likely they will try to block the API for this use case. This has happened to other integrations as well. I would suggest to make increase this to somewhere between 1-5 minutes.

We can also make this poll interval configurable so a user can choose the interval themselves.

@jschlyter If you don't have time, I'd be happy to implement this as well after you're done refactoring.

**Comment by wouterhardeman** [comment]
While looking into it I noticed that there is caching, but I think because of new the shorter-lived access tokens it seems to be retrieving a new token every 15 seconds (the SCAN_INTERVAL). See: https://github.com/pypolestar/polestar_api/blob/12ba7a5a39581eedd3886a545de8f684482fe326/custom_components/polestar_api/pypolestar/polestar.py#L118

**Comment by jschlyter** [comment]
Thanks for the heads up. Please review https://github.com/pypolestar/polestar_api/pull/210 and https://github.com/pypolestar/polestar_api/pull/211.
