### ISSUE TITLE
API token expires and does not refresh

### ISSUE THREAD

**Issue by crg-n** [pypolestar/polestar_api#215]
Hi, I have been having some issues recently with the API token stopping refreshing. I saw there were some commits related to the token refresh, and so this afternoon I have also tried running the most up to date code from here, but the issue persists. I can only get a single update by reloading the integration. It identifies that the API token will expire in 5 minutes and then (as expected) it expires 5 minutes later and nothing updates until I reload the integration again.

Any ideas? Happy to provide the relevant logs if someone signposts me to where the most useful ones are. Thanks!

**Comment by crg-n** [comment]
Digging into this a little more, practically every second line of my debugging logs is "Skipping update, already in progress"

Looking at the code (as a total noob) this looks like it gets caught at:

```
        if not self.updating.acquire(blocking=False):
            self.logger.debug("Skipping update, already in progress")
            return
```

which prevents it from ever getting to the refresh token step:

```
       try:
            if self.auth.need_token_refresh():
                await self.auth.get_token(refresh=True)
```

The only other thing notable thing I can see in the logs is:

`2024-11-09 14:18:15.036 ERROR (MainThread) [custom_components.polestar_api.polestar] Unexpected Error on update data 'PolestarAuth' object has no attribute 'logger'`

But my custom_components/polestar_api/pypolestar/auth.py does have:         `self.logger = _LOGGER.getChild(unique_id) if unique_id else _LOGGER` from dd7f27e.

**Comment by jschlyter** [comment]
I'm working on cleaning up updates now, hope to have a new release tomorrow.

**Comment by jschlyter** [comment]
Pre-release 1.9.0rc1 now published

**Comment by mariwing** [comment]
Unfortunately it does not seem to fix it. No updates on the sensors after initial loading.

**Comment by fblix** [comment]
maybe its helpful having a look over here?
https://github.com/evcc-io/evcc/issues/17186

**Comment by jschlyter** [comment]
Yes, this has already been addressed. Some issues with caching left, sorting that out now.

**Comment by jschlyter** [comment]
https://github.com/pypolestar/polestar_api/releases/tag/1.9.0rc3 released, please test
