### ISSUE TITLE
Car not found

### ISSUE THREAD

**Issue by jgelon** [pypolestar/polestar_api#223]
Hi, i am trying to add my PS2 to this addon. However I am getting a Car not found error. 

Account is added to car
Account credentials are valid so is VIN.

Not sure what I am doing wrong or what step I missed. Any help is appreciated. Is there maybe an API I can use to check my connected vehicles?

**Comment by leeyuentuen** [comment]
Try login with your account and see if the car is listed, not with the app but on the website

**Comment by vaxjool** [comment]
I have the same error. Can logon on polestars website, no issue. Car is listed.

version: 12.11.0 and 1.8.0b1

**Comment by jschlyter** [comment]
> I have the same error. Can logon on polestars website, no issue. Car is listed.

Are you listed as owner for the car? Can you also test with 1.9.0?

**Comment by vaxjool** [comment]
Version 1.9.0 works!
