### ISSUE TITLE
Car data does not update since 1.9.0rc1

### ISSUE THREAD

**Issue by gjsiiger** [pypolestar/polestar_api#224]
My cars data does not update since 1.9.0rc1 (running rc2) now.
I reloaded the integration and the new data shows up right away.
API log about token refresh keeps working.

Will enable debug, disconnect the car from charger and reconnect a bit later to generate some logs.

**Comment by jschlyter** [comment]
This is a known problem and have a fix pending, please try if you can #222.

**Comment by jschlyter** [comment]
https://github.com/pypolestar/polestar_api/releases/tag/1.9.0rc3 released, please test

**Comment by gjsiiger** [comment]
Seems to be working quite ok, have disconnected and re-connected charger and within a few minutes the sensors are updated. If other can confirm we can close this issue.
