### ISSUE TITLE
Polestar API token expires every 15 seconds

### ISSUE THREAD

**Issue by pabutterworth** [pypolestar/polestar_api#226]
Is it expected that I have this log message every 15 seconds? I hope this isn’t contacting the Polestar service that often!

Polestar API Token Expires At  changed to 2024-11-11 20:28:07
20:23:23 - 6 seconds ago

**Comment by wouterhardeman** [comment]
This issue has been fixed but not fully released yet. You can install pre-release version 1.9.0rc3 for the fix!

**Comment by jschlyter** [comment]
Fixed in https://github.com/pypolestar/polestar_api/releases
