### ISSUE TITLE
Problems when updating to 1.9.0

### ISSUE THREAD

**Issue by mji11** [pypolestar/polestar_api#234]
Restarting after an 1.9.0 update gives a warning for "Invalid config". The log is attached. Am I doing something wrong?

[home-assistant_2024-11-13T15-45-38.743Z.log](https://github.com/user-attachments/files/17735243/home-assistant_2024-11-13T15-45-38.743Z.log)

**Comment by jschlyter** [comment]
Can you see what version of `gql` you got in your Home Assistant environment?

**Comment by jschlyter** [comment]
Looks like a corrupt file somewhere.

**Comment by mji11** [comment]
How can I find the version of gql?
My system is fully updated, so I assume I have the latest available version.

**Comment by jschlyter** [comment]
> How can I find the version of gql? My system is fully updated, so I assume I have the latest available version.

You should have the latest version, but for some reason the downloaded files are corrupt. Are you running in a container?

**Comment by mji11** [comment]
I'm running a virtual machine, VirtualBox. Would you have an idea on how to replace the corrupted files?

**Comment by jschlyter** [comment]
Are you running HassOS, a container or plain Python inside your VM? For both HassOS and container you should be able to reinstall keeping your configuration and data. Plain Python needs some more work.

**Comment by mji11** [comment]
Just got the problem resolved after updating the core to 11.2.
