### ISSUE TITLE
Entities not updating regularly anymore after newest update

### ISSUE THREAD

**Issue by dgebhardt** [pypolestar/polestar_api#240]
I see positive API status codes and updates happen every once in a while (I speak of days), but not frequently enough to actually show valuable information. That was different until the last update. 

Anyone else experiencing that?

P.S: with the update my old device was no longer working and a second one was added to HA. That was working. I switched to that and disabled the old one. 
![IMG_5669](https://github.com/user-attachments/assets/e0707c9a-7a27-4e4c-9ff9-b53b5970b333)

**Comment by jschlyter** [comment]
Yes entity unique IDs has changed in one of the last updates, that's why the old ones did not work. The new identifiers are designed to work with multiple cars and even the same car twice in the same instance.

**Comment by dgebhardt** [comment]
And any idea on the update intervals?

**Comment by jschlyter** [comment]
The integration updates from the Polestar API once every minute, how often "they" talk to the car I don't know. I understand they now work with a "digitial twin" instead of polling.

**Comment by dgebhardt** [comment]
Ok, that's interesting. Anyone else experiencing, that there are sometimes more than 2 days w/o any update? In HA it still shows charge levels from 2 days ago (after that I was driving the car, charging the car etc.).

**Comment by jschlyter** [comment]
What model of car is this? Is the app updated or does it also show old information?

**Comment by dgebhardt** [comment]
It's a Polestar 2, 2024. 
The app is always up to date and in sync with the car. So is the info I can see in the Polstar WebApp. I just tried it and the last info there was from 8.40 AM this morning, when I last used the car. In HA it was still 2 days old.

I then tried a restarted HA and after that Polestar API info was updated and now also shows the info with the 8.40 AM timestamp.

**Comment by jschlyter** [comment]
Everything working now?

**Comment by dgebhardt** [comment]
No, unfortunately, the issues keeps coming back. With a newly restarted HA, it works for a bit, but after a couple of hours it breaks. Have turned on debug logging now and will check if I can see something there.

**Comment by jschlyter** [comment]
If you have not yet upgraded to the latest pre-release, please do and test again so you're not testing old code.

**Comment by dgebhardt** [comment]
I did that now and will observe the behaviour. Will let you know. Thanks for your support!

**Comment by dgebhardt** [comment]
For the last 2 days it worked again with the pre-release version of the integration.

**Comment by jschlyter** [comment]
Very good, 1.10.0 now released.
