### ISSUE TITLE
API unexpected failure when reinstalling Polestar API 10.0.0 in HA 2024.12.1

### ISSUE THREAD

**Issue by johanhallberg** [pypolestar/polestar_api#261]
Hi,

I tried to reinstall the Polestar  API as I got errors when upgraded Home Assistant from 2024.11.2 to 2024.12.1. I entered the Polestar ID and Password during installation, but got "API unexpected failure". No difference if I put in VIN. I've tried multiple times. It worked perfectly in 2024.11.x and before that. Has anyone else seen this? 

Polestar API Version 1.10.0
Homeassistant versions: 
	• Core 2024.12.1 
	• Supervisor 2024.11.4 
	• Operating System 14.0 
	• Frontend 20241106.2

```
This error originated from a custom integration.

Logger: custom_components.polestar_api.config_flow
Source: custom_components/polestar_api/config_flow.py:47
integration: Polestar API (documentation, issues)
First occurred: 11:23:05 (1 occurrences)
Last logged: 11:23:05

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 143, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 61, in async_init
    await self.auth.get_token()
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 85, in get_token
    if (code := await self._get_code()) is None:
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 140, in _get_code
    if resumePath is None:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'resumePath' where it is not associated with a value
```

**Comment by BJReplay** [comment]
I just ran into the same issue.  I intentionally restarted my HA (as I had an error in my watchtower config that was restarting a container that should be excluded), and I needed to restart the entire docker compose stack.

I saw the same symptoms as you mentioned.  The integration did not come up after restart, and re-installing did not help.

What is interesting, though, is that I had updated to 2024.12.1 somewhat earlier.

Could it be a change to the auth returning something different quite recently, causing this error, as I have been restarting my dev environment for hours this afternoon, and not hit this error.

Bedtime on this side of the world, so a problem for tomorrow.

**Comment by motionist** [comment]
I see similar behavior although started unexpectedly this morning. API is returning unavailable.
Updated to 2024.12.1 yesterday afternoon (CET 16:08) and ran without problems until restart due to another installation this morning (Wyze HACS),

**Comment by bunjamin1982** [comment]
I have noted a similar error upon restarting home assistant following the update to 2024.21.1. The logs have the following error: **Unexpected Error on update data cannot access local variable 'resumePath' where it is not associated with a value**

I have reinstalled the integration and the error persists

**Comment by jschlyter** [comment]
Polestar has once again changed their login logic, perhaps trying to block external integrations. Patches welcome!

**Comment by jschlyter** [comment]
Update: Polestar started to use PKCE for authentication. I can now get the code, but I cannot yet exchange it for a token. The quest continues!

**Comment by Fuellhase** [comment]
Same Problem with my Polestar here in Germany: "API unexpected failure".

**Comment by motionist** [comment]
It seems we are dependent of Polestar who in turn is trying their best to keep anyone out of the data - including the brilliant developers of this API. 
I would suggest users of this API interface to raise Your voice in the Polestar community to make Polestar aware that we are merely trying to integrate **our** data into a platform which we control and manage.

**Comment by jschlyter** [comment]
> It seems we are dependent of Polestar who in turn is trying their best to keep anyone out of the data - including the brilliant developers of this API. I would suggest users of this API interface to raise Your voice in the Polestar community to make Polestar aware that we are merely trying to integrate **our** data into a platform which we control and manage.

For the record, I do not believe Polestar is trying to keep us out. They are however improving their identity solution and that currently breaks things when done without coordination. I have a meeting with Polestar later this week and hope to make progress then.

**Comment by jkkataja** [comment]
> > It seems we are dependent of Polestar who in turn is trying their best to keep anyone out of the data - including the brilliant developers of this API. I would suggest users of this API interface to raise Your voice in the Polestar community to make Polestar aware that we are merely trying to integrate **our** data into a platform which we control and manage.
> 
> For the record, I do not believe Polestar is trying to keep us out. They are however improving their identity solution and that currently breaks things when done without coordination. I have a meeting with Polestar later this week and hope to make progress then.

Excellent that you have managed to schedule a meeting. Please let us know if we can somehow help you with it.

**Comment by motionist** [comment]
> > It seems we are dependent of Polestar who in turn is trying their best to keep anyone out of the data - including the brilliant developers of this API. I would suggest users of this API interface to raise Your voice in the Polestar community to make Polestar aware that we are merely trying to integrate **our** data into a platform which we control and manage.
> 
> For the record, I do not believe Polestar is trying to keep us out. They are however improving their identity solution and that currently breaks things when done without coordination. I have a meeting with Polestar later this week and hope to make progress then.

Excellent - I would emphasize to Polestar that unannounced changes does have a tendency to cause incidents in the IT world - incidents relating products or services have a tendency to lower user satisfaction. 

It's fairly simple customer management.

**Comment by nanoq66** [comment]
> Excellent - I would emphasize to Polestar that unannounced changes does have a tendency to cause incidents in the IT world - incidents relating products or services have a tendency to lower user satisfaction.
> 
Fair point, but this is nothing that is based on any interface contracts etc. I suppose e.g. Tibber got informed ahead, but these hobby projects like this are usually not supported by corporations. It is awesome that @jschlyter is given the chance to have a talk with Polestar, so it shows they are actually willing to support. It would be nice to have updated API spec available though, without signing a NDA or other agreement.

**Comment by rostbeule** [comment]
> Some tips for whoever is going to fix this integration:
> 
> **1. Initialize authentication** The initial call to `https://polestarid.eu.polestar.com/as/authorization.oauth2` should now include PKCE related properties:
> 
> ```
> {
>   'response_type' => 'code',
>   'client_id' => 'l3oopkc_10',
>   'redirect_uri' => 'https://www.polestar.com/sign-in-callback',
>   'state' => '<uuid>', // Polestar will return this with the code but value can be ignored
>   'code_challenge' => '<sha256-hash-of-code-verifier>,
>   'scope' => 'openid profile email customer:attributes',
>   'code_challenge_method' => 'S256'
> }
> ```
> 
> **2. Exchange code for access token** POST to `https://polestarid.eu.polestar.com/as/token.oauth2`
> 
> ```
> {
>   'grant_type' => 'authorization_code',
>   'code' => '<code-returned-by-polestar>',
>   'code_verifier' => '<your-code-verifier>',
>   'client_id' => 'l3oopkc_10',
>   'redirect_uri' => 'https://www.polestar.com/sign-in-callback'
> }
> ```
> 
> https://www.oauth.com/oauth2-servers/pkce/authorization-request/

He's absolutely right - tested it - works like a charm <3

**Comment by rostbeule** [comment]
> Indeed works perfectly, fixed the iOS widgets.
> 
> see [niklasvieth/polestar-ios-medium-widget@1bd45af](https://github.com/niklasvieth/polestar-ios-medium-widget/commit/1bd45af8b1f7f34d48682941e05737d07efe65e1)


RLY? O_o ... :D
```
const CODE_VERIFIER = "polestar-ios-widgets-are-enabled-by-scriptable";
```

**Comment by Fuellhase** [comment]
Thanks for the info.So my question now: Will there be an API-Update on one of the next Days?GreetingsPeter FüllhaseZur Quelle 1448341 AltenbergeMail: ***@***.*** 10.12.2024 um 19:33 schrieb Thomas Leininger ***@***.***>:﻿

Indeed works perfectly, fixed the iOS widgets.
see ***@***.***

RLY? O_o ... :D
const CODE_VERIFIER = "polestar-ios-widgets-are-enabled-by-scriptable";

**Comment by BJReplay** [comment]
> Some tips for whoever is going to fix this integration:

I may have a chance to test and submit a PR today, but have a busy day scheduled.

The values mentioned match those I captured - which confirms that they are not client specific (mine: Android app).

Thanks for sharing.

**Comment by BJReplay** [comment]
> I have a meeting with Polestar later this week and hope to make progress then.

@jschlyter have you got any work in progress to share? I couldn't see any branches yesterday when I looked. I might be able to get a chance to get this going today, so building from any start you have made will help.

**Comment by jschlyter** [comment]
Please try #262

**Comment by jschlyter** [comment]
I've tested #262 here and everything works fine. I do like at least one more positive review before merging and creating a new release.

**Comment by jschlyter** [comment]
https://github.com/pypolestar/polestar_api/releases/tag/1.11.0rc1 ready for public testing

**Comment by 3shirts** [comment]
Yep, 1.11.0rc1 working for me too.

**Comment by Fuellhase** [comment]
Yes! It’s working again.THX!👍👍👍👍👍Peter FüllhaseZur Quelle 1448341 AltenbergeMail: ***@***.*** 10.12.2024 um 22:46 schrieb Jakob Schlyter ***@***.***>:﻿
https://github.com/pypolestar/polestar_api/releases/tag/1.11.0rc1 ready for public testing

**Comment by motionist** [comment]
Working for me - great effort

**Comment by bunjamin1982** [comment]
Thank you very much for the fast turnaround! Working perfectly!
