### ISSUE TITLE
Charge Limit viewing in the plugin.

### ISSUE THREAD

**Issue by nthbooth** [pypolestar/polestar_api#32]
First of all thank you for all the hard effort from everyone who has worked on this plugin. It is awesome and so good to see the polestar now in the home assistant tool.

I was wondering if charge limit is exposed anywhere in the API? I can't see it in the values reported. 

I want to be able to switch off the charger when the charge limit is reached. I can now query the Current charge level as but what the limit is would be essential to ensure that I always top up the car to what it is set to charge to. 

Many thanks for considering my request.

Nick

**Comment by leeyuentuen** [comment]
i want to to like charge limit and lock unlock the car and climate activate, but there information I didn't found it (yet) on the reverse engineering of the polestar mobile app. so if someone can find the data, I'll like to implement.

**Comment by nthbooth** [comment]
Looking on the web app and the mobile, I can't find the charge limit in the application or web at all.... So I am guessing this is not going to be possible. 

Nick

**Comment by leeyuentuen** [comment]
on the android app, i could set the max rate between 6A till 32A

**Comment by loebse** [comment]
Same on iOS but the question is charging limit in terms of Ampere or SoC %?

**Comment by nthbooth** [comment]
I was looking for the % of the car battery. 80% or 90% rather than a charge rate of 6A etc.

**Comment by loebse** [comment]
And this is unfortunately not available on web, Android, iOS.

**Comment by leeyuentuen** [comment]
very disappointed from polestar without any support.

**Comment by loebse** [comment]
It obviously depends on your setup but what I personally do is the following:

- Read the current SoC from this integration
- Set the target SoC via a helper in HA
- Set charging power of my wallbox to 0 A when current SoC = target SoC

**Comment by jschlyter** [comment]
Changing the charge limit is not possible with web app credentials.
